### ISSUE TITLE
Errors with Node v8.15.1 on OSX

### ISSUE THREAD

**Issue by ansoni-san** [ahwayakchih/crx3#1]
Has this been tested on OSX?

I'm getting:

```
Pauliinas-iMac:syncmotion-chrome anthony$ crx3 --key syncmotion-plugin --crx ../syncmotion-plugin.crx -- build/manifest.json
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1233:7)
    at scanList (/usr/local/lib/node_modules/crx3/lib/getFilePaths.js:78:19)
    at scanList (/usr/local/lib/node_modules/crx3/lib/getFilePaths.js:81:39)
    at getFilePaths (/usr/local/lib/node_modules/crx3/lib/getFilePaths.js:28:10)
    at writeCRX3File (/usr/local/lib/node_modules/crx3/lib/writeCRX3File.js:52:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/crx3/bin/crx3.js:12:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

I get this error when running all of the examples, and also using the code interface instead of command line.

**Comment by ansoni-san** [comment]
Code example I've tried which produces the same error: 

```js
#!/usr/bin/env node

const crx3 = require('crx3');

crx3(['./build/manifest.json'], {
  keyPath: './syncmotion-plugin.pem',
  crxPath: '../syncmotion-plugin.crx',
  zipPath: '../syncmotion-plugin.zip'
})
  .then(() => console.log('done'))
	.catch(console.error)
;
```

**Comment by ahwayakchih** [comment]
Thanks for the report.

Which version of Node.js did you use?

I do not have access to OSX (or any Apple products), so it would be great if you could help with debugging it there.

I tried it on Alpine Linux like this:
```sh
cd example/
../bin/crx3.js --key example-extension.pem --crx ../example-extension.crx -- example-extension/manifest.json
```
It worked OK.

I also tried this (just in case the problem was with relative paths):
```js
#!/usr/bin/env node

const crx3 = require('../');

crx3(['./example-extension/manifest.json'], {
  keyPath: './example-extension.pem',
  crxPath: '../example-extension.crx',
  zipPath: '../example-extension.zip'
})
  .then(() => console.log('done'))
	.catch(console.error)
;
```
And it worked OK (when run from within `example/` subdirectory).

Could you run this command line and let me know the results?
```sh
node -e 'console.log(require("fs").readdirSync(process.cwd(), {withFileTypes: true}));'
```
You can run it in some temporary directory, with at least one file.
When i run it in example directory of this project, i get this:
```txt
[ Dirent { name: 'example-extension', [Symbol(type)]: 2 },
  Dirent { name: 'example-extension.crx', [Symbol(type)]: 1 },
  Dirent { name: 'example-extension.pem', [Symbol(type)]: 1 },
  Dirent { name: 'example-extension.zip', [Symbol(type)]: 1 },
  Dirent { name: 'example.js', [Symbol(type)]: 1 } ]
```
If you'll get something similar (array of Dirent objects, each with `name` property), then at least this part works OK :).

**Comment by SentientClee** [comment]
Confirmed that this package works on macOS Mojave (Version 10.14.4) with Node.js (v11.12.0). Thanks for making this library. Still a little worried about backwards compatibility with older browser versions and new CRXV3 extensions.

**Comment by ahwayakchih** [comment]
@SentientClee thanks! I did not upload any extension to Google webstore yet, so not sure how they resolve old vs new format there. They must know which browser version is requesting the install, so i'm guessing they serve extension package in supported format.

Last change to crx3.proto was around two years ago:
https://chromium.googlesource.com/chromium/src.git/+log/refs/heads/master/components/crx_file/crx3.proto

Last change to crx3_file component was 3 months ago:
https://chromium.googlesource.com/chromium/src.git/+log/refs/heads/master/components/crx_file

It looks like Chromium's built-in CRX creator was switched to CRX3 on Oct 16, 2017:
https://chromium.googlesource.com/chromium/src.git/+/b8bc9f99ef4ad6223dfdcafd924051561c05ac75
So it should have had support for v3 by then.

Since Chrome and Chromium have auto-update, i'm guessing pretty much every version in use today supports CRX3 by now. Still, it's just a guess - i do not have old versions for a quick test, sorry :(.

**Comment by ansoni-san** [comment]
@ahwayakchih The project I'm using runs on node **8.15.1**.

**Comment by ahwayakchih** [comment]
@ansoni-san thanks for info. Unfortunately this project does not support Node.js versions older than v11.6.0. At least not for now.
I'm almost sure it's possible to make it work for v10.x, but i'm guessing that for v8.x it would require either much more code or many more dependencies :(. It's doable of course, but i'm not sure it's worth it because, i imagine, it's usable mostly for automated builds, in which case it's should be easy to setup "build crx" task using version different than the one used for rest of the project.
Patches are welcome of course :). Although i would prefer to create separate branch for supporting older versions of Node.js.
